import type { User, Repository, Document, Tag, RepositoryMember, Invitation, DashboardStats } from '@/types';

// Mock Current User
export const mockCurrentUser: User = {
  id: '550e8400-e29b-41d4-a716-446655440000',
  email: 'demo@linktoss.com',
  username: 'demouser',
  name: '데모 유저',
  avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=demo',
  bio: '링크를 효율적으로 관리하는 개발자',
  emailVerified: true,
  createdAt: '2025-01-01T00:00:00Z',
};

// Mock Users
export const mockUsers: User[] = [
  mockCurrentUser,
  {
    id: '550e8400-e29b-41d4-a716-446655440001',
    email: 'john@example.com',
    username: 'johndev',
    name: 'John Developer',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=john',
    bio: 'Frontend Developer',
    emailVerified: true,
    createdAt: '2024-12-01T00:00:00Z',
  },
  {
    id: '550e8400-e29b-41d4-a716-446655440002',
    email: 'sarah@example.com',
    username: 'sarahdesigner',
    name: 'Sarah Designer',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=sarah',
    bio: 'UI/UX Designer',
    emailVerified: true,
    createdAt: '2024-11-15T00:00:00Z',
  },
];

// Mock Tags
export const mockTags: Tag[] = [
  { id: 'tag-1', name: 'react', color: '#61DAFB', documentCount: 12 },
  { id: 'tag-2', name: 'nextjs', color: '#000000', documentCount: 8 },
  { id: 'tag-3', name: 'typescript', color: '#3178C6', documentCount: 15 },
  { id: 'tag-4', name: 'design', color: '#FF6B6B', documentCount: 6 },
  { id: 'tag-5', name: 'ui-ux', color: '#4ECDC4', documentCount: 9 },
  { id: 'tag-6', name: 'tutorial', color: '#95E1D3', documentCount: 20 },
  { id: 'tag-7', name: 'documentation', color: '#F38181', documentCount: 14 },
];

// Mock Repositories
export const mockRepositories: Repository[] = [
  {
    id: 'repo-1',
    userId: mockCurrentUser.id,
    parentId: null,
    name: '개발 자료',
    description: '프론트엔드 개발 관련 자료 모음',
    icon: '💻',
    isPublic: false,
    slug: 'dev-resources',
    position: 0,
    documentCount: 24,
    subRepositoryCount: 2,
    createdAt: '2025-01-05T10:00:00Z',
    updatedAt: '2025-10-10T15:30:00Z',
    role: 'owner',
  },
  {
    id: 'repo-2',
    userId: mockCurrentUser.id,
    parentId: 'repo-1',
    name: 'React',
    description: 'React 학습 자료 및 참고 문서',
    icon: '⚛️',
    isPublic: false,
    slug: 'react',
    position: 0,
    documentCount: 12,
    subRepositoryCount: 0,
    createdAt: '2025-01-10T10:00:00Z',
    updatedAt: '2025-10-09T14:00:00Z',
    role: 'owner',
  },
  {
    id: 'repo-3',
    userId: mockCurrentUser.id,
    parentId: 'repo-1',
    name: 'TypeScript',
    description: 'TypeScript 관련 자료',
    icon: '📘',
    isPublic: false,
    slug: 'typescript',
    position: 1,
    documentCount: 8,
    subRepositoryCount: 0,
    createdAt: '2025-01-12T10:00:00Z',
    updatedAt: '2025-10-08T11:00:00Z',
    role: 'owner',
  },
  {
    id: 'repo-4',
    userId: mockCurrentUser.id,
    parentId: null,
    name: '디자인 레퍼런스',
    description: 'UI/UX 디자인 영감을 얻을 수 있는 사이트 모음',
    icon: '🎨',
    isPublic: true,
    slug: 'design-references',
    position: 1,
    documentCount: 18,
    subRepositoryCount: 0,
    createdAt: '2025-02-01T10:00:00Z',
    updatedAt: '2025-10-07T16:20:00Z',
    role: 'owner',
  },
  {
    id: 'repo-5',
    userId: mockUsers[1].id,
    parentId: null,
    name: '팀 프로젝트',
    description: '팀 협업용 링크 모음',
    icon: '🤝',
    isPublic: false,
    slug: 'team-project',
    position: 0,
    documentCount: 15,
    subRepositoryCount: 1,
    createdAt: '2025-03-01T10:00:00Z',
    updatedAt: '2025-10-10T09:00:00Z',
    role: 'editor',
    user: mockUsers[1],
  },
  {
    id: 'repo-6',
    userId: mockCurrentUser.id,
    parentId: null,
    name: '북마크',
    description: '나중에 읽을 것들',
    icon: '📚',
    isPublic: false,
    slug: 'bookmarks',
    position: 2,
    documentCount: 32,
    subRepositoryCount: 0,
    createdAt: '2025-01-20T10:00:00Z',
    updatedAt: '2025-10-10T18:00:00Z',
    role: 'owner',
  },
];

// Mock Documents
export const mockDocuments: Document[] = [
  {
    id: 'doc-1',
    repositoryId: 'repo-2',
    userId: mockCurrentUser.id,
    title: 'React 공식 문서',
    url: 'https://react.dev',
    content: '# React\n\nReact는 사용자 인터페이스를 만들기 위한 JavaScript 라이브러리입니다.\n\n## 주요 특징\n- 컴포넌트 기반\n- 선언적\n- 한 번 배워서, 어디서나 사용하기',
    contentPreview: 'React는 사용자 인터페이스를 만들기 위한 JavaScript 라이브러리입니다.',
    linkMetadata: {
      ogTitle: 'React',
      ogImage: 'https://react.dev/images/og-home.png',
      ogDescription: 'The library for web and native user interfaces',
      ogUrl: 'https://react.dev',
      favicon: 'https://react.dev/favicon.ico',
      siteName: 'React',
      type: 'website',
    },
    tags: [mockTags[0]],
    createdAt: '2025-01-15T10:00:00Z',
    updatedAt: '2025-01-15T10:00:00Z',
  },
  {
    id: 'doc-2',
    repositoryId: 'repo-2',
    userId: mockCurrentUser.id,
    title: 'React Hooks 완벽 가이드',
    url: 'https://react.dev/reference/react',
    content: '# React Hooks\n\nHooks는 React 16.8에서 도입된 새로운 기능입니다.\n\n## useState\nstate를 함수 컴포넌트에서 사용할 수 있게 해줍니다.\n\n## useEffect\n부수 효과를 수행할 수 있게 해줍니다.',
    contentPreview: 'Hooks는 React 16.8에서 도입된 새로운 기능입니다. state와 생명주기 기능을...',
    linkMetadata: {
      ogTitle: 'React Reference',
      ogImage: 'https://react.dev/images/og-home.png',
      ogDescription: 'API reference for React',
    },
    tags: [mockTags[0], mockTags[5]],
    createdAt: '2025-02-01T14:00:00Z',
    updatedAt: '2025-02-05T11:00:00Z',
  },
  {
    id: 'doc-3',
    repositoryId: 'repo-3',
    userId: mockCurrentUser.id,
    title: 'TypeScript Handbook',
    url: 'https://www.typescriptlang.org/docs/handbook/intro.html',
    content: '# TypeScript Handbook\n\nTypeScript는 JavaScript의 상위 집합 언어입니다.\n\n타입 안정성을 제공하여 대규모 애플리케이션 개발에 적합합니다.',
    contentPreview: 'TypeScript는 JavaScript의 상위 집합 언어입니다.',
    linkMetadata: {
      ogTitle: 'TypeScript: Documentation',
      ogDescription: 'TypeScript extends JavaScript by adding types',
      siteName: 'TypeScript',
    },
    tags: [mockTags[2], mockTags[6]],
    createdAt: '2025-01-20T09:00:00Z',
    updatedAt: '2025-01-20T09:00:00Z',
  },
  {
    id: 'doc-4',
    repositoryId: 'repo-4',
    userId: mockCurrentUser.id,
    title: 'Dribbble - 디자인 영감',
    url: 'https://dribbble.com',
    content: '# Dribbble\n\n디자이너들의 작품을 공유하는 플랫폼\n\n## 활용법\n- 트렌드 파악\n- 색상 조합 참고\n- UI 패턴 학습',
    contentPreview: '디자이너들의 작품을 공유하는 플랫폼',
    linkMetadata: {
      ogTitle: 'Dribbble - Discover the World's Top Designers',
      ogDescription: 'Find Top Designers & Creative Professionals',
      siteName: 'Dribbble',
    },
    tags: [mockTags[3], mockTags[4]],
    createdAt: '2025-02-10T10:00:00Z',
    updatedAt: '2025-02-10T10:00:00Z',
  },
  {
    id: 'doc-5',
    repositoryId: 'repo-5',
    userId: mockUsers[1].id,
    title: 'Figma Design System',
    url: 'https://www.figma.com/design',
    content: '# 팀 디자인 시스템\n\n프로젝트에서 사용하는 디자인 시스템 링크',
    contentPreview: '프로젝트에서 사용하는 디자인 시스템 링크',
    linkMetadata: {
      ogTitle: 'Figma Design',
    },
    tags: [mockTags[3]],
    createdAt: '2025-03-05T10:00:00Z',
    updatedAt: '2025-03-05T10:00:00Z',
  },
  {
    id: 'doc-6',
    repositoryId: 'repo-1',
    userId: mockCurrentUser.id,
    title: 'Next.js 공식 문서',
    url: 'https://nextjs.org/docs',
    content: '# Next.js Documentation\n\nNext.js는 React 프레임워크입니다.\n\n## App Router\n새로운 라우팅 시스템',
    contentPreview: 'Next.js는 React 프레임워크입니다.',
    linkMetadata: {
      ogTitle: 'Next.js Documentation',
      ogDescription: 'The React Framework for the Web',
    },
    tags: [mockTags[0], mockTags[1]],
    createdAt: '2025-01-25T10:00:00Z',
    updatedAt: '2025-01-25T10:00:00Z',
  },
];

// Mock Repository Members
export const mockRepositoryMembers: RepositoryMember[] = [
  {
    id: 'member-1',
    repositoryId: 'repo-5',
    userId: mockUsers[1].id,
    user: mockUsers[1],
    role: 'owner',
    invitedBy: null,
    invitedAt: '2025-03-01T10:00:00Z',
    acceptedAt: '2025-03-01T10:00:00Z',
    status: 'accepted',
  },
  {
    id: 'member-2',
    repositoryId: 'repo-5',
    userId: mockCurrentUser.id,
    user: mockCurrentUser,
    role: 'editor',
    invitedBy: mockUsers[1].id,
    invitedAt: '2025-03-02T10:00:00Z',
    acceptedAt: '2025-03-02T14:00:00Z',
    status: 'accepted',
  },
];

// Mock Invitations
export const mockInvitations: Invitation[] = [
  {
    id: 'invite-1',
    repository: {
      id: 'repo-7',
      userId: mockUsers[2].id,
      parentId: null,
      name: '디자인 시스템 레퍼런스',
      description: '다양한 디자인 시스템 모음',
      icon: '🎨',
      isPublic: false,
      slug: 'design-system-ref',
      position: 0,
      documentCount: 25,
      subRepositoryCount: 0,
      createdAt: '2025-09-01T10:00:00Z',
      updatedAt: '2025-10-05T10:00:00Z',
      user: mockUsers[2],
    },
    invitedBy: mockUsers[2],
    role: 'editor',
    invitedAt: '2025-10-09T10:00:00Z',
    status: 'pending',
  },
];

// Mock Dashboard Stats
export const mockDashboardStats: DashboardStats = {
  overview: {
    repositoryCount: 5,
    documentCount: 89,
    publicRepositoryCount: 1,
    tagCount: 7,
  },
  recentDocuments: mockDocuments.slice(0, 5),
  frequentRepositories: mockRepositories.slice(0, 3),
};
